#!/usr/bin/env bash 

# Update package list and install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create a temporary index.html file containing "Hello World!"
touch /var/www/html/index.html
chmod 666 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

service nginx start
