#!/usr/bin/env bash
# configure Nginx server to listen and run on port 80 of all server's active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
