#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080 default_server/g' /etc/nginx/sites-available/default
systemctl stop nginx
systemctl start nginx
